version: "3.9"
    
x-www-volume:  
  &www-volume
  type: bind
  source: ./
  target: /var/www/html/

services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - ./local/var/lib/mysql:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
  phpmyadmin:
    container_name: ${PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 2000M
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT}:80

  wordpress:
    container_name: ${PROJECT_NAME}_wordpress
    depends_on:
      - db
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WP_VERSION: ${WP_VERSION}
    ports:
      - ${WP_PORT}:80
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST}
    volumes:
      - *www-volume  
